version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/addon-options"
    versions:
    - "> 3.4.11"
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.3
    - 6.2.0
  - dependency-name: "@cypress/webpack-preprocessor"
    versions:
    - 5.6.0
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.20
  - dependency-name: stylelint
    versions:
    - 13.11.0
  - dependency-name: stylelint-prettier
    versions:
    - 1.2.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 28.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: "@testing-library/cypress"
    versions:
    - 7.0.4
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.15
  - dependency-name: start-server-and-test
    versions:
    - 1.12.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
  - dependency-name: cypress
    versions:
    - 6.3.0
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.15
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
