export const primary = "#3ed6f0";
export const secondary = "#252e3e";
export const gray = "#e2e2e2";
export const white = "#f7f7f7";
export const primaryFontFamily = "\"DIN Condensed Bold\"";
export const secondaryFontFamily = "\"Encode Sans\"";
export const borderRadius = "3px";
export const navBarHeight = "65px";
export const navBarTopGutterHeight = "20px";
