pull_request_rules:
  - name: Auto-merge successful Dependabot upgrades
    conditions:
      - author=dependabot-preview[bot]
      - '#changes-requested-reviews-by=0'
      - status-success=now
      - status-success=deploy/netlify
      - 'status-success=ci/circleci: build_and_test'
      - 'status-success=ci/circleci: cypress_install'
      - 'status-success=ci/circleci: run'
      - status-success=codeclimate
      - status-success=codeclimate/diff-coverage
      - status-success=codeclimate/total-coverage
    actions:
      merge:
        method: rebase
        strict: true
