queue_rules:
  - name: default
    queue_conditions:
      - author=dependabot[bot]
      - '#changes-requested-reviews-by=0'
      - 'status-success=Vercel – operation-code'
      - 'status-success=Vercel – storybook'
      - 'status-success=CI / lint'
      - 'status-success=CI / unit_tests'
      - 'status-success=Playwright Tests / test'
      - status-success=codeclimate/diff-coverage
      - status-success=codeclimate/total-coverage
    merge_conditions:
      - 'status-success=Vercel – operation-code'
      - 'status-success=Vercel – storybook'
      - 'status-success=CI / lint'
      - 'status-success=CI / unit_tests'
      - 'status-success=Playwright Tests / test'
      - status-success=codeclimate/diff-coverage
      - status-success=codeclimate/total-coverage
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
