pull_request_rules:
  - name: Auto-merge successful Dependabot upgrades
    conditions:
      - author=dependabot-preview[bot]
      - '#changes-requested-reviews-by=0'
      - 'status-success=Vercel - operation-code'
      - 'status-success=Vercel - storybook'
      - 'status-success=ci/circleci: lint'
      - 'status-success=ci/circleci: unit_tests'
      - 'status-success=cypress: all tests'
    actions:
      merge:
        method: rebase
        strict: true
